import { colors } from '@/theme/colors'
import { fonts } from '@/theme/fonts'

export const fabStyles = {
  button: {
    position: 'fixed' as const,
    bottom: 'calc(28px + env(safe-area-inset-bottom, 0px))',
    right: '20px',
    height: '58px',
    width: '58px',
    borderRadius: '999px',
    border: 'none',
    backgroundColor: colors.salmon,
    cursor: 'pointer',
    overflow: 'hidden',
    boxShadow: '0 6px 20px rgba(161, 77, 54, 0.35)',
    zIndex: 40,
    transition: 'width 0.3s ease, box-shadow 0.15s ease, transform 0.15s ease',
  },
  buttonHover: {
    width: '220px',
    boxShadow: '0 8px 28px rgba(161, 77, 54, 0.45)',
  },
  buttonActive: {
    transform: 'scale(0.96)',
    boxShadow: '0 3px 12px rgba(161, 77, 54, 0.30)',
  },
  iconArea: {
    position: 'absolute' as const,
    right: 0,
    top: 0,
    width: '58px',
    height: '58px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    position: 'absolute' as const,
    left: 0,
    top: 0,
    bottom: 0,
    right: '58px',
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '20px',
    color: colors.white,
    fontFamily: fonts.family.primary,
    fontWeight: fonts.weight.bold,
    fontSize: '14px',
    whiteSpace: 'nowrap' as const,
    opacity: 0,
    transition: 'opacity 0.15s ease',
    lineHeight: 1,
    pointerEvents: 'none' as const,
  },
  labelVisible: {
    opacity: 1,
    transition: 'opacity 0.2s ease 0.15s',
  },
}
