name: Auto-merge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  auto-merge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    # Only run for PRs that have the 'auto-merge' label
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" \
            --repo "${{ github.repository }}" \
            --auto \
            --squash
